### PR TITLE
New feature: Caching instagram response option

### PR DESCRIPTION
**Pull request by m0nclous**

### CODE REVIEW

**Comment by mahotilo** [comment]
I have tested this commit and can confirm its efficiency. There are no errors after a hundred of page reload in a row.

**Comment by jsanahuja** [comment]
I have invited you to be contributor @mahotilo so you could review the code too :)

**Comment by mahotilo** [comment]
@jsanahuja,
really, it is an honour for me. I will try my best, but I'll refrain from rash actions :)

**Review by mahotilo — APPROVED** [review]

**Comment by jsanahuja** [comment]
I made some small changes:

- According to [Semantic Versioning](https://semver.org/), any new feature should change the x.Y.z number so in this case it should be 1.5.0. As I think this feature should be enabled by default, I have set a default `cache_time` to 2 hours and as this would change the 1.4.1 version behavior we will release the 2.0.0 version.
- I have changed the code to use the localStorage API (setItem and getItem) instead of treating it as an object.
- Changed the localStorage keys to use username/tag instead of the url.

Thank you, really a great feature and a good work :)

Should solve #99 #96 #95 #94 among others.

**Review by jsanahuja — APPROVED** [review]

**Review by mahotilo — COMMENTED** [review]
Is not 2 hours too long for cache expire?
I do not know what an IG limit is, but maybe it is possible to start from 60 min?
In any case, the default cache on is a great solution.

**Comment by jsanahuja** [comment]
> Is not 2 hours too long for cache expire?

I don't really know, depends on how often does people publish on their Instagram accounts. If you have instagramFeed cached and I publish a picture it would take you 2 hours at most to see it in the website. If you guys think this is too much we can change it

**Comment by mahotilo** [comment]
>If you have instagramFeed cached and I publish a picture it would take you 2 hours at most to see it in the website. If you guys think this is too much we can change it

I am just afraid of a new wave of *bugs* like "I have published post, but the script doesn't show it" :)

**Review by csanahuja — APPROVED** [review]

**Comment by jsanahuja** [comment]
> > If you have instagramFeed cached and I publish a picture it would take you 2 hours at most to see it in the website. If you guys think this is too much we can change it
> 
> I am just afraid of a new wave of "bugs" like "I have published post, but the script doesn't show it" :)

I think that is better than  "Stopped working" haha

**Pull request merged**
