### PR TITLE
New feature: random feed

### PR DESCRIPTION
**Pull request by HMellor**
Is enabled by setting `total: true` and will show `items: 8` random posts from the `total: 12` most recent posts.

### CODE REVIEW

**Comment by jsanahuja** [comment]
We will accept this change if its done following the contributing guidelines we just added 95c5ed8

Please, do it removing `total` and take always X random `items` out of 12. Also, make a more clear and efficient random array generation.

Thanks

**Comment by HMellor** [comment]
Can you please re open this pull request so that I can make changes to it?

**Comment by HMellor** [comment]
@jsanahuja I think this should be ready now, let me know what you think :)

**Comment by jsanahuja** [comment]
There is still a lot of formatting changes in `jquery.instagramFeed.js`. Also, you don't need to shuffle the entire array to display X random non repeated items

**Comment by HMellor** [comment]
The formatting is just removing trailing white-space and adding spaces where they should be to improve readability. If it really bothers you I can revert it but it would be effort for nothing.

As for shuffling the entire array, this has been addressed by [d429e96](https://github.com/jsanahuja/jquery.instagramFeed/pull/39/commits/d429e96aaa010d10cdaa1c2bb66580cde5de2544).

**Pull request closed without merging**
